AWSTemplateFormatVersion: "2010-09-09"
Description: Testing cloudformation parameters capabilities

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "EC2 Instance Configuration"
        Parameters:
          - EC2AMID
          - InstanceType
      - Label:
          default: "S3 Bucket Configuration"
        Parameters:
          - S3BucketNameParameter

Parameters:
  EC2AMID:
    Type: String
    Description: The AMI ID to use for the EC2 instance
    Default: ami-00a929b66ed6e0de6
    AllowedValues:
      - ami-00a929b66ed6e0de6 
      - ami-07a6f770277670015
  InstanceType:
    Type: String
    Description: The EC2 instance type
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
  S3BucketNameParameter:
    Type: String
    Description: The name of the S3 bucket

Resources:
  JoseEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2AMID
      InstanceType: !Ref InstanceType 
  JoseS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketNameParameter